import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';

/**
 * CF01–CF20 — THE CLOUDFLARE DEPLOYMENT CONTRACT, asserted from source.
 *
 * Stage 5C-1A-R1 selected Workers Static Assets and froze one architectural
 * rule that is invisible in review and expensive to get wrong:
 *
 *   CLOUDFLARE DOES NOT APPLY `_headers` TO RESPONSES GENERATED BY WORKER CODE.
 *
 * CAD Fixer therefore ships NO Worker code. If someone later adds a `main`
 * entrypoint or sets `run_worker_first`, the cross-origin isolation headers
 * stop being sent, the browser withholds `SharedArrayBuffer`, and conservative
 * repair fails closed — IN PRODUCTION ONLY, which is precisely the failure
 * class Stage 5B exists to prevent. Nothing in the type system can catch that.
 * These tests are the guard.
 *
 * They read CONFIGURATION, not a build, so they run in the ordinary unit suite
 * and cannot silently pass when `dist` is absent. The two that genuinely need
 * build output (CF17–CF19) say so and skip explicitly rather than pretending.
 */

const REPO_ROOT = join(import.meta.dirname, '..');
const CONFIG_PATH = join(REPO_ROOT, 'wrangler.jsonc');
const HEADERS_SOURCE = join(REPO_ROOT, 'apps', 'web', 'public', '_headers');
const ASSETSIGNORE_SOURCE = join(REPO_ROOT, 'apps', 'web', 'public', '.assetsignore');
const DIST = join(REPO_ROOT, 'apps', 'web', 'dist');

/**
 * JSONC allows comments AND trailing commas, neither of which `JSON.parse`
 * accepts. Wrangler's own schema sets `allowTrailingCommas`, and Prettier
 * inserts them, so a parser here that rejected them would fail on a file
 * Wrangler reads perfectly well. Strings are preserved so a `//` inside a value
 * (a URL, say) is never mistaken for a comment.
 */
function parseJsonc(text: string): unknown {
  let out = '';
  let inString = false;
  let inLineComment = false;
  let inBlockComment = false;
  for (let i = 0; i < text.length; i += 1) {
    /*
     * `noUncheckedIndexedAccess` is on, so indexing yields `string | undefined`
     * even though `i < text.length` guarantees a character. Defaulting to '' is
     * correct for the lookahead too: past the end there is no next character,
     * and '' matches none of the comparisons below.
     */
    const c = text[i] ?? '';
    const next = text[i + 1] ?? '';
    if (inLineComment) {
      if (c === '\n') {
        inLineComment = false;
        out += c;
      }
      continue;
    }
    if (inBlockComment) {
      if (c === '*' && next === '/') {
        inBlockComment = false;
        i += 1;
      }
      continue;
    }
    if (inString) {
      out += c;
      if (c === '\\') {
        out += next;
        i += 1;
      } else if (c === '"') {
        inString = false;
      }
      continue;
    }
    if (c === '"') {
      inString = true;
      out += c;
      continue;
    }
    if (c === '/' && next === '/') {
      inLineComment = true;
      i += 1;
      continue;
    }
    if (c === '/' && next === '*') {
      inBlockComment = true;
      i += 1;
      continue;
    }
    out += c;
  }
  /* Trailing commas: `,` followed only by whitespace before `}` or `]`. */
  return JSON.parse(out.replace(/,(\s*[}\]])/g, '$1')) as unknown;
}

const rawConfig = readFileSync(CONFIG_PATH, 'utf8');
const config = parseJsonc(rawConfig) as Record<string, unknown>;
const assets = config.assets as Record<string, unknown> | undefined;
const headersText = readFileSync(HEADERS_SOURCE, 'utf8');

/** A `_headers` directive, ignoring comments and blank lines. */
function headerValue(name: string): string | undefined {
  for (const line of headersText.split('\n')) {
    const trimmed = line.trim();
    if (trimmed === '' || trimmed.startsWith('#')) continue;
    const separator = trimmed.indexOf(':');
    if (separator === -1) continue;
    if (trimmed.slice(0, separator).trim().toLowerCase() !== name.toLowerCase()) continue;
    return trimmed.slice(separator + 1).trim();
  }
  return undefined;
}

/** The directives that apply under a given path rule, in file order. */
function rulesFor(pathPattern: string): string[] {
  const collected: string[] = [];
  let active = false;
  for (const line of headersText.split('\n')) {
    const trimmed = line.trim();
    if (trimmed === '' || trimmed.startsWith('#')) continue;
    if (!line.startsWith(' ') && !line.startsWith('\t')) {
      active = trimmed === pathPattern;
      continue;
    }
    if (active) collected.push(trimmed);
  }
  return collected;
}

describe('CF01–CF08 — Wrangler configuration', () => {
  it('CF01: wrangler.jsonc parses', () => {
    expect(config).toBeTypeOf('object');
    expect(config.name).toBe('cad-fixer');
    expect(config.compatibility_date).toMatch(/^\d{4}-\d{2}-\d{2}$/);
  });

  it('CF02: declares no Worker entrypoint, and no Worker source file exists', () => {
    expect(config.main).toBeUndefined();
    /*
     * The config is only half the guarantee: a file Wrangler could pick up by
     * convention is the other half.
     */
    for (const candidate of [
      'worker.ts',
      'worker.js',
      'src/worker.ts',
      'src/worker.js',
      'src/index.ts',
      '_worker.js',
      join('apps', 'web', 'dist', '_worker.js'),
    ]) {
      expect(existsSync(join(REPO_ROOT, candidate))).toBe(false);
    }
  });

  it('CF03: workers_dev is false, so no stable production route exists', () => {
    expect(config.workers_dev).toBe(false);
  });

  it('CF04: preview_urls is explicitly true', () => {
    /*
     * Not cosmetic. `preview_urls` defaults to the value of `workers_dev`, so
     * omitting it here would inherit `false` and produce no preview URL at all.
     */
    expect(config.preview_urls).toBe(true);
  });

  it('CF05: assets.directory is exactly the production build output', () => {
    expect(assets?.directory).toBe('./apps/web/dist');
  });

  it('CF06: run_worker_first is false and cannot become truthy', () => {
    /*
     * The single switch that would route requests through Worker code and
     * bypass `_headers`. An array of route patterns is truthy too, so the
     * assertion is on the exact value rather than on falsiness.
     */
    expect(assets?.run_worker_first).toBe(false);
    expect(rawConfig).not.toMatch(/"run_worker_first"\s*:\s*true/);
    expect(rawConfig).not.toMatch(/"run_worker_first"\s*:\s*\[/);
  });

  it('CF07: declares no route, no routes and no custom domain', () => {
    expect(config.route).toBeUndefined();
    expect(config.routes).toBeUndefined();
    expect(config.custom_domain).toBeUndefined();
    expect(config.workers_dev).not.toBe(true);
  });

  it('CF08: declares no bindings or server-side resources', () => {
    for (const forbidden of [
      'kv_namespaces',
      'd1_databases',
      'r2_buckets',
      'durable_objects',
      'queues',
      'services',
      'vars',
      'secrets_store_secrets',
      'hyperdrive',
      'ai',
      'vectorize',
      'analytics_engine_datasets',
      'browser',
      'mtls_certificates',
      'dispatch_namespaces',
      'send_email',
      'triggers',
      'crons',
      'observability',
    ]) {
      expect(config[forbidden], `${forbidden} must not be configured`).toBeUndefined();
    }
    /* An assets binding exists only to read assets FROM Worker code. */
    expect(assets?.binding).toBeUndefined();
  });
});

describe('CF09–CF16 — the _headers isolation and cache contract', () => {
  it('CF09: Cross-Origin-Opener-Policy is exactly same-origin', () => {
    expect(headerValue('Cross-Origin-Opener-Policy')).toBe('same-origin');
  });

  it('CF10: Cross-Origin-Embedder-Policy is exactly require-corp', () => {
    expect(headerValue('Cross-Origin-Embedder-Policy')).toBe('require-corp');
  });

  it('CF11: Cross-Origin-Resource-Policy is exactly same-origin', () => {
    expect(headerValue('Cross-Origin-Resource-Policy')).toBe('same-origin');
  });

  it('CF12: X-Content-Type-Options is exactly nosniff', () => {
    expect(headerValue('X-Content-Type-Options')).toBe('nosniff');
  });

  it('CF13: Referrer-Policy is exactly no-referrer', () => {
    expect(headerValue('Referrer-Policy')).toBe('no-referrer');
  });

  it('CF14: the HTML shell is revalidated, never immutable', () => {
    const html = rulesFor('/index.html');
    expect(html).toContain('Cache-Control: no-cache');
    expect(html.join('\n')).not.toMatch(/immutable/);
  });

  it('CF15: hashed assets are immutably cacheable', () => {
    expect(rulesFor('/assets/*')).toContain('Cache-Control: public, max-age=31536000, immutable');
  });

  it('CF16: no Content-Security-Policy has been added', () => {
    /*
     * Stage 5C-1A deferred CSP deliberately. A policy added without qualifying
     * module workers, `wasm-unsafe-eval` and `blob:` would break the product in
     * production only.
     */
    expect(headersText).not.toMatch(/Content-Security-Policy/i);
  });

  it('CF09-16: the five global headers apply to every path', () => {
    const global = rulesFor('/*');
    expect(global).toEqual([
      'Cross-Origin-Opener-Policy: same-origin',
      'Cross-Origin-Embedder-Policy: require-corp',
      'Cross-Origin-Resource-Policy: same-origin',
      'X-Content-Type-Options: nosniff',
      'Referrer-Policy: no-referrer',
    ]);
  });
});

describe('CF17–CF20 — build output and the deployable set', () => {
  const built = existsSync(join(DIST, 'index.html'));

  it('CF17: the build copies _headers into the deployable directory', () => {
    if (!built) {
      expect.unreachable('run `npm run build` before this suite');
    }
    expect(existsSync(join(DIST, '_headers'))).toBe(true);
    expect(readFileSync(join(DIST, '_headers'), 'utf8')).toBe(headersText);
  });

  it('CF18: .assetsignore excludes source maps and never excludes _headers', () => {
    const ignore = readFileSync(ASSETSIGNORE_SOURCE, 'utf8');
    const rules = ignore
      .split('\n')
      .map((l) => l.trim())
      .filter((l) => l !== '' && !l.startsWith('#'));
    expect(rules).toContain('*.map');
    /*
     * `_headers` must stay OUT of this file. Wrangler already withholds it from
     * the public asset set on its own, and listing it here risks a future
     * reader concluding it is optional configuration.
     */
    expect(rules).not.toContain('_headers');
    for (const keep of ['*.js', '*.css', '*.wasm', '*.html', 'assets', 'assets/*']) {
      expect(rules).not.toContain(keep);
    }
    if (built) {
      expect(existsSync(join(DIST, '.assetsignore'))).toBe(true);
    }
  });

  it('CF19: every runtime asset is present and no source map is deployable', () => {
    if (!built) {
      expect.unreachable('run `npm run build` before this suite');
    }
    const assetsDir = join(DIST, 'assets');
    const names = readFileSync(join(DIST, 'index.html'), 'utf8');
    expect(names).toMatch(/<script[^>]+src="\/assets\/index-[^"]+\.js"/);
    expect(existsSync(assetsDir)).toBe(true);
    /*
     * Source maps are still BUILT — `sourcemap: true` is untouched, so local
     * debugging is unaffected. They are excluded at UPLOAD time, which is what
     * `.assetsignore` expresses and what CF18 asserts.
     */
  });

  it('CF20: the shipped Geogram kernel is the qualified artifact', () => {
    const kernel = join(
      REPO_ROOT,
      'packages',
      'self-intersection-kernel',
      'artifacts',
      'self-intersection.wasm',
    );
    expect(existsSync(kernel)).toBe(true);
  });
});
